---
version: '3.5'
networks:
  ai_sidekick:
    external: true
services:
  sidekick-server:
    # command: tail -f /dev/null
    networks:
      - ai_sidekick
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
    - 8888:8888
    restart: on-failure:0
    env_file:
      - .env
  weaviate:
    networks:
      - ai_sidekick
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.18.2
    ports:
    - 8080:8080
    expose:
      - 8080
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      ENABLE_MODULES: 'text2vec-openai'
      CLUSTER_HOSTNAME: 'node1'